using Microsoft.AspNetCore.Mvc;
using Microservice.API.Extensions;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;
using Asp.Versioning;
using Asp.Versioning.Builder;
using System.Reflection;

namespace Microservice.API;
/// <summary>
/// API Services Registration
/// 
/// Configures:
/// - Controllers
/// - Swagger/OpenAPI
/// - Global Exception Handling
/// - Logging
/// - Configuration
/// </summary>
public static class ApiRegistration
{
    public static IServiceCollection AddApiServices(
        this IServiceCollection services,
        IConfigurationManager configuration,
        IWebHostEnvironment hostEnvironment)
    {
        // Add services to the container
        services.AddControllers();

        // Configure API Versioning - Simple approach
        var versioningBuilder = services.AddApiVersioning(options =>
        {
            options.DefaultApiVersion = new ApiVersion(1, 0);
            options.AssumeDefaultVersionWhenUnspecified = true;
            options.ReportApiVersions = true;
            options.ApiVersionReader = ApiVersionReader.Combine(
                new UrlSegmentApiVersionReader(),           // /api/v1/examples
                new QueryStringApiVersionReader("api-version"), // ?api-version=1.0
                new HeaderApiVersionReader("X-Version")        // X-Version: 1.0
            );
        });

        // Add API Explorer for versioned documentation
        versioningBuilder.AddApiExplorer(options =>
        {
            options.GroupNameFormat = "'v'VVV";
            options.SubstituteApiVersionInUrl = true;
        });

        // Register global exception handler (Modern .NET 10 approach)
        services.AddGlobalExceptionHandler();

        // Configure Swagger/OpenAPI for multiple versions
        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen(c =>
        {
            // Version 1 - Current stable version
            c.SwaggerDoc("v1", new OpenApiInfo
            {
                Title = "Microservice API",
                Version = "v1.0",
                Description = "Microservice API with CQRS pattern and Result error handling - Version 1.0 (Stable)",
                Contact = new OpenApiContact
                {
                    Name = "API Team",
                    Email = "api@example.com"
                }
            });

            // Version 2 - Enhanced version
            c.SwaggerDoc("v2", new OpenApiInfo
            {
                Title = "Microservice API",
                Version = "v2.0",
                Description = "Microservice API with enhanced features - Version 2.0 (Preview)",
                Contact = new OpenApiContact
                {
                    Name = "API Team",
                    Email = "api@example.com"
                }
            });

            c.CustomSchemaIds(type => type.FullName!.Replace("+", "."));

            // XML comments� generated by <GenerateDocumentationFile>true</GenerateDocumentationFile>
            var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
            var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            if (File.Exists(xmlPath))
                c.IncludeXmlComments(xmlPath);

            // -- Bearer auth -----------------------------------------------
            // Adds the lock icon + "Authorize" button to the Swagger UI.
            c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                Name         = "Authorization",
                Type         = SecuritySchemeType.Http,
                Scheme       = "bearer",
                BearerFormat = "JWT",
                In           = ParameterLocation.Header,
                Description  =
                    "JWT Bearer token. " +
                    "Obtain one from POST /api/v1/auth/token (dev only). " +
                    "The 'Bearer ' prefix is added automatically by Swagger UI."
            });

            // Apply the Bearer requirement globally via a document filter.
            // A bare AddSecurityRequirement(...) serializes an EMPTY requirement under
            // Microsoft.OpenApi 2.x because the scheme reference has no host document to
            // resolve against; the filter has access to the document so the reference
            // resolves and Swagger UI actually attaches the Authorization header.
            c.DocumentFilter<BearerSecurityDocumentFilter>();
        });

        configuration
            .AddJsonFile($"appsettings.json", optional: true)
            .AddJsonFile($"appsettings.{hostEnvironment.EnvironmentName}.json", optional: true);

        configuration.AddEnvironmentVariables();

        //if (hostEnvironment.IsDevelopment() && File.Exists("../.env.local"))
        //    configuration.AddDotNetEnv("../.env.local");

        services.AddJwtAuthentication(configuration);
        services.AddObservability(configuration, hostEnvironment);
        services.AddCustomHealthChecks(configuration);
        services.AddCustomRateLimiting(configuration);

        services.AddCors(options =>
        {
            options.AddPolicy("DefaultCors", policy =>
            {
                if (hostEnvironment.IsDevelopment() || hostEnvironment.EnvironmentName == "Testing")
                {
                    policy.AllowAnyOrigin()
                          .AllowAnyHeader()
                          .AllowAnyMethod();
                }
                else
                {
                    policy.WithOrigins("http://")
                          .AllowAnyHeader()
                          .AllowAnyMethod();
                }
            });
        });

        return services;
    }
}

/// <summary>
/// Adds a global Bearer security requirement to the generated OpenAPI document.
/// Implemented as a document filter so the scheme reference resolves against the
/// host document (Microsoft.OpenApi 2.x), which a bare AddSecurityRequirement does not.
/// </summary>
internal sealed class BearerSecurityDocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        swaggerDoc.Security =
        [
            new OpenApiSecurityRequirement
            {
                { new OpenApiSecuritySchemeReference("Bearer", swaggerDoc), [] }
            }
        ];
    }
}
