-- ════════════════════════════════════════════════════════════════════════
-- Schema DAPPER del aggregate Example (aislado de EF Core).
--
-- Aislamiento por ORM:
--   · EF Core  → schema 'ef'     (ef.Examples / ef.ExampleItems)  — vía migraciones EF.
--   · Dapper   → schema 'dapper' (dapper.examples / dapper.example_items) — este script.
--
-- Convención Dapper: snake_case + Dapper.DefaultTypeMap.MatchNamesWithUnderscores.
-- Defaults de status/created_at/updated_at los aporta la BD para que los INSERT
-- mínimos de los repos Dapper funcionen.
--
-- Aplicar:
--   psql "$CONNSTR" -f Microservice.Infrastructure/Persistence/Scripts/dapper_schema.sql
-- ════════════════════════════════════════════════════════════════════════
CREATE SCHEMA IF NOT EXISTS dapper;

-- ── Aggregate root ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dapper.examples (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   uuid         NOT NULL,
    name        text         NOT NULL,
    description text,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_examples_public_id ON dapper.examples (public_id);

-- ── Child entity ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dapper.example_items (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    example_id  integer       NOT NULL REFERENCES dapper.examples (id) ON DELETE CASCADE,
    public_id   uuid          NOT NULL,
    label       varchar(150)  NOT NULL,
    quantity    integer       NOT NULL,
    status      integer       NOT NULL DEFAULT 1,            -- ExampleItemStatus.Pending (=1)
    created_at  timestamptz   NOT NULL DEFAULT now(),
    updated_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_example_items_public_id  ON dapper.example_items (public_id);
CREATE INDEX        IF NOT EXISTS ix_example_items_example_id ON dapper.example_items (example_id);
